version: 0.2
phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/cicd-demo-0.0.1-SNAPSHOT.jar)
      - pwd
artifacts:
  files:
    - build/libs/cicd-demo-0.0.1-SNAPSHOT.jar
    - build_scripts/appspec.yml   # CodeDeploy 적용 시 추가
    - build_scripts/start.sh    # CodeDeploy 적용 시 추가
  discard-paths: yes
cache:
  paths:
    - '/root/.gradle/**/*'